#%RAML 1.0 NamedExample
{
    "id": 1,
    "firstName": "Juan",
    "lastName": "Jiménez",
    "address": "Plaza de España, 1",
    "postal": "28924",
    "country": "Spain",
    "miles": 100,
    "type": "personal",
    "creationDate": "2008-09-08T22:47:31+02:00"
}