#%RAML 1.0 NamedExample
[
  {
    "firstName": "Juan",
    "lastName": "Jiménez",
    "address": "Plaza de España, 1",
    "postal": "28924",
    "country": "Spain",
    "miles": 100,
    "type": "personal"
  },
  {
    "firstName": "Pedro",
    "lastName": "Jiménez",
    "address": "Plaza de España, 1",
    "postal": "28924",
    "country": "Spain",
    "miles": 100,
    "type": "personal"
  }
]